[workspace]
members = ["cargo:."]

[dist]
cargo-dist-version = "0.32.0"
installers = ["shell", "powershell"]
targets = ["aarch64-unknown-linux-gnu", "x86_64-unknown-linux-gnu", "aarch64-apple-darwin", "aarch64-pc-windows-gnullvm", "x86_64-pc-windows-gnu"]
dist-dir = "target/distribution"
install-path = "CARGO_HOME"
install-updater = true
