name: Build Silence

on:
    workflow_dispatch:
    release:
        types: [created]

permissions:
    contents: write
    actions: write

jobs:
    build-frontend:
        name: Build frontend
        runs-on: ubuntu-latest
        if: |
            github.event_name == 'workflow_dispatch' ||
            (github.event_name == 'release' &&
             contains(fromJson('["nv0skar"]'), github.actor))
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest

            - name: Cache Bun dependencies
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.bun/install/cache
                      node_modules
                  key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
                  restore-keys: |
                      ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
                      ${{ runner.os }}-bun-

            - name: Install frontend dependencies
              run: bun install

            - name: Build frontend
              run: bun run build

            - name: Upload frontend dist
              uses: actions/upload-artifact@v4
              with:
                  name: frontend
                  path: target/
                  retention-days: 7

    trigger-release:
        needs: build-frontend
        uses: ./.github/workflows/release.yml
        with:
            tag: ${{ inputs.tag || github.event.release.tag_name }}
